# Dev
org.gradle.jvmargs=-Xmx2G

# Mod - All field required.
mod.name=Way2Homes
mod.id=way2homes
mod.group=dev.sshear
mod.version=1.1.0
mod.author=Sammy Shear
mod.description=A simple mod and plugin combo that automatically creates waypoints at player's homes.
mod.license=MPL-2.0
mod.github=https://github.com/sammyshear/way2homes

# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge, paper
stonecutter_enabled_common_versions=1.21.1,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11
stonecutter_enabled_fabric_versions=1.21.1,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11
stonecutter_enabled_neoforge_versions=1.21.1,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11
stonecutter_enabled_paper_versions=1.21.1,1.21.3,1.21.4,1.21.5,1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11

# The below field are intentionally left blank,
# to edit, please edit gradle.properties for each versions.

# Java
java.version=21

# Minecraft
minecraft_version=[VERSIONED]
min_minecraft_version=[VERSIONED]

# Mappings
deps.parchment=[VERSIONED]

# Fabric https://fabricmc.net/versions.html
deps.fabric-loader=[VERSIONED]
deps.fabric-api=[VERSIONED]

# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=[VERSIONED]

# Dependencies
deps.modmenu=[VERSIONED]