# Dev
org.gradle.jvmargs=-Xmx2G

# Mod - All field required.
mod.name=ExampleMod
mod.id=examplemod
mod.group=com.example
mod.version=1.0.0
mod.author=Author
mod.description=Description of Example Mod.
mod.license=MPL-2.0
mod.github=https://github.com/sammyshear/multiloader-and-paper-stonecutter

# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge, forge, paper
stonecutter_enabled_common_versions=1.20.1, 1.21.1
stonecutter_enabled_fabric_versions=1.20.1, 1.21.1
stonecutter_enabled_forge_versions=1.20.1
stonecutter_enabled_neoforge_versions=1.21.1
stonecutter_enabled_paper_versions=1.20.1, 1.21.1

# The below field are intentionally left blank,
# to edit, please edit gradle.properties for each versions.

# Java
java.version=

# Minecraft
minecraft_version=
min_minecraft_version=

# Mappings
deps.parchment=

# Fabric https://fabricmc.net/versions.html
deps.fabric-loader=
deps.fabric-api=

# Forge
deps.forge=

# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=

# Dependencies
deps.modmenu=
deps.yacl=