# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge, paper

# Java
java.version=21

# Minecraft
minecraft_version=1.21.11
min_minecraft_version=1.21.11

# Mappings
deps.parchment=2025.

# Fabric
deps.fabric_loader=0.18.2
deps.fabric_api=0.139.5

# NeoForge
deps.neoforge=21.11.6-beta

# Dependencies
deps.modmenu=11.0.1
deps.jmap=2.0.0-1.21.11-SNAPSHOT
deps.essentials=2.21.2
deps.huskhomes=4.9.9
