# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge, paper

# Java
java.version=21

# Minecraft
minecraft_version=1.21.11
min_minecraft_version=1.21.11

# Mappings
deps.parchment=2025.12.20

# Fabric
deps.fabric_loader=0.18.4
deps.fabric_api=0.141.2

# NeoForge
deps.neoforge=21.11.37-beta

# Dependencies
deps.modmenu=16.0.0
deps.xaeros=25.3.5
deps.xaeros_mc_version=1.21.11
deps.jmap=2.0.0-1.21.11-SNAPSHOT
deps.essentials=2.21.2
deps.huskhomes=4.9.10
