# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge, paper

# Java
java.version=21

# Minecraft
minecraft_version=1.21.4
min_minecraft_version=1.21.4

# Mappings
deps.parchment=2025.03.23

# Fabric
deps.fabric_loader=0.18.2
deps.fabric_api=0.119.4

# NeoForge
deps.neoforge=21.4.156

# Dependencies
deps.modmenu=11.0.1
deps.xaeros=25.2.10
deps.xaeros_mc_version=1.21.4
deps.jmap=2.0.0-1.21.4-SNAPSHOT
deps.essentials=2.21.2
deps.huskhomes=4.9.9
