# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge, paper

# Java
java.version=21

# Minecraft
minecraft_version=1.21.8
min_minecraft_version=1.21.8

# Mappings
deps.parchment=2025.09.14

# Fabric
deps.fabric_loader=0.18.2
deps.fabric_api=0.136.1

# NeoForge
deps.neoforge=21.8.52

# Dependencies
deps.modmenu=11.0.1
deps.xaeros=25.2.15
deps.xaeros_mc_version=1.21.8
deps.jmap=2.0.0-1.21.9-SNAPSHOT
deps.essentials=2.21.2
deps.huskhomes=4.9.9
