name: ${modName}
version: ${modVersion}
main: dev.sshear.way2homes.Way2Homes
description: ${modDescription}
api-version: ${minecraftVersion}
dependencies:
  server:
    Essentials:
      load: BEFORE
      required: false
      join-classpath: true
    HuskHomes:
      load: BEFORE
      required: false
      join-classpath: true